# Generated by Django 5.0.1 on 2024-02-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_notes_note_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='note_user_name',
            field=models.CharField(default='name', max_length=150),
        ),
    ]
